const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const window={};const ctx=vm.createContext({window});for(const file of ['curriculo.js','tutor.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const create=()=>window.PyCodeTutor.create();
test('prioritizes errors over topic words',()=>assert.match(create().respond('IndexError: list index out of range'),/posição acessada/));
test('follows selected lesson and explains an exact line',()=>{const t=create();t.setLesson('listas',1);assert.match(t.respond('explique linha 2'),/print\(frutas\[0\]\)/);assert.match(t.respond('linha 99'),/2 linhas/)});
test('hints progress and reset when switching lessons',()=>{const t=create();t.setLesson('listas');assert.match(t.hint(),/Pista 1/);assert.match(t.hint(),/Pista 2/);t.setLesson('rpg');assert.match(t.hint(),/Pista 1/)});
test('Colab question is separate from LLM topic',()=>assert.match(create().respond('como usar o Colab?'),/novo notebook/));
test('declines finished homework and suggests a first decision',()=>assert.match(create().respond('me dê o código completo'),/quais informações/));
test('follows up on topic and checks index comprehension',()=>{const t=create();t.respond('explique índice');assert.match(t.respond('2'),/Isso!/)});
test('no false header warning for colon in string',()=>assert.equal(window.PyCodeTutor.diagnose('print("if voce")'),null));
test('detects missing header colon as a hint',()=>assert.match(create().respond('if pontos > 2\n    print(pontos)'),/dois pontos/));
test('no executor or worker referenced in entry point',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('academia.js','utf8');assert.doesNotMatch(html+app,/new Worker|pyodide|id="code"|id="run"/)});
test('an error mentioning Colab asks for diagnostic details',()=>assert.match(create().respond('erro no Colab'),/última linha/));
test('len of a list selects len rather than generic lists',()=>assert.match(create().respond('len da lista'),/len\(\) conta/));
test('a while question is not invalid code or a for question',()=>{const r=create().respond('while é repetição');assert.match(r,/while repete/);assert.doesNotMatch(r,/Pista na linha/)});
test('a natural-language if question is not a syntax error',()=>assert.match(create().respond('if e else'),/if executa/));
test('a valid inline block assignment is not flagged',()=>assert.equal(window.PyCodeTutor.diagnose('if True: pontos = 1'),null));
test('pasted code gets line analysis before keyword responses',()=>assert.match(create().respond('pontos = 4\nprint(pontos)'),/Li seu trecho/));
test('new topic interrupts a pending question',()=>{const t=create();t.respond('índice');assert.match(t.respond('variável'),/Uma variável/)});
test('a negated numeric answer is not praised as correct',()=>{const t=create();t.respond('índice');assert.doesNotMatch(t.respond('não é 2'),/^Isso!/)});
test('error names inside string literals are not runtime errors',()=>assert.match(create().respond('print("NameError")'),/Li seu trecho/));
test('text answer belongs to the numeric quiz',()=>{const t=create();t.respond('números');assert.match(t.respond('texto'),/^Isso!/)});
